### ISSUE TITLE
needs conda-forge recipe

### ISSUE THREAD

**Issue by yarikoptic** [jwodder/pytest-fail-slow#1]
so that datalad release could be tested on conda-forge builds 
ref: https://github.com/datalad/datalad/pull/6273#issuecomment-991155773

**Comment by jwodder** [comment]
Conda-forge PR created: https://github.com/conda-forge/staged-recipes/pull/18754

**Comment by jwodder** [comment]
Now on conda-forge: https://github.com/conda-forge/pytest-fail-slow-feedstock
