### ISSUE TITLE
Opt-in to failing slow tests when `pytest-fail-slow` is installed?

### ISSUE THREAD

**Issue by mdhaber** [jwodder/pytest-fail-slow#10]
Thanks for writing `pytest-fail-slow`! We're trying it out on two of SciPy's CI jobs to identify very slow in PRs before they are merged.

Initially, I thought that slow tests would only fail if `fail_slow` were provided as a command line argument. However, now that I've added some exceptions via the `@pytest.mark.fail_slow` mark, marked tests are _always_ subject to the specified time limit if `pytest-fail-slow` is installed. Because of variability in test times on different platforms, this is undesirable; we really only want to use `pytest-fail-slow` on certain CI jobs or when a developer manually opts in - whether `pytest-fail-slow` is installed or not. 

I tried using `pytest_configure` in `conftest.py` to replace the `fail_slow` mark with a dummy unless a command line argument is present, but I couldn't get that to work - the mark is not even present in `config.getini('markers')`, so I can't really replace it. 

Do I need to learn more about how to configure `pytest`, or can you suggest another way to use `pytest-fail-slow` only if a command line option is present? Would this be a feature you'd be willing to support/document?

**Comment by jwodder** [comment]
> Initially, I thought that slow tests would only fail if `fail_slow` were provided as a command line argument.

Yes, as you've discovered, this is not the case.  The effect of the `--fail-slow` option is essentially to add `@pytest.mark.fail_slow(...)` to every test that doesn't already have it, and the marker always does its thing when the plugin is installed.  Can you suggest a way the documentation could have made this clearer?

> Would this be a feature you'd be willing to support/document?

How about this: I add an `enabled: bool = True` keyword argument to the `pytest-fail-slow` markers; when `enabled` is set to `False` on a marker, the marker will do nothing for the current test run.  Would that meet your needs?

**Comment by mdhaber** [comment]
> Can you suggest a way the documentation could have made this clearer?

It is not surprising in retrospect; it's just not what I had in mind. But if there would be additional documentation for the new opt-in feature we're discussing, that would be an easy place to make the default behavior very explicit.

> Would that meet your needs?

I'm not sure I understand how I'd set the marker `enabled=False` - where would that go? 

In case it helps, the solution i had in mind was an option in some test configuration file that would not use `pytest-fail-slow`, even if installed, unless a keyword argument was present. 

BTW, right now we register a placeholder mark for `fail_slow` if `pytest-fail-slow` is not installed.

**Comment by jwodder** [comment]
> I'm not sure I understand how I'd set the marker `enabled=False` - where would that go?

It's not a marker; it's an argument to the `fail_slow` and `fail_slow_setup` markers.  You'd use it like this:

```python
@pytest.mark.fail_slow(5, enabled=some_condition())
def test_thingy():
    ...
```

where `some_condition()` is a boolean expression, just like you'd pass to a `skipif` or `xfail` marker.  (Note that I'm not planning to support [condition strings](https://docs.pytest.org/en/8.2.x/historical-notes.html#conditions-as-strings-instead-of-booleans)) at this time.)  If you want `fail_slow` markers to only take effect if `--slow` is given on the command line, you should be able to just do:

```python
@pytest.mark.fail_slow(5, enabled=pytest.config.getvalue("slow"))
def test_thingy():
    ...
```

**Comment by mdhaber** [comment]
I see. I'd rather not *have* to specify the condition as an argument of every marker,  but that would work, and it would be a more general solution than what I had in mind.

**Comment by jwodder** [comment]
The `enabled` keyword argument has been added to the marker in v0.6.0, out now.

**Comment by mdhaber** [comment]
Thanks! The tip about `"config.getoption('--fail-slow') is not None"` is particularly helpful!
