### ISSUE TITLE
Add a command line option to apply a `fail_slow_setup` option to all tests

### ISSUE THREAD

**Issue by ElPincheTopo** [jwodder/pytest-fail-slow#13]
This request is similar to #12.

Adding an option to apply a slow setup mark to all tests would be really useful. This would allow for a big project to enforce duration limits very easily and only have to apply the decorator to tests that need to deviate from the default value.

It would also be very useful to be able to set this options in the pytest configuration file or in the project.toml files. This would allow for users to notice that their test is taking too long when running tests manually and not only when running them in a CI environment or something like that that can be configured to always use the command line option.

**Comment by ElPincheTopo** [comment]
Sorry about that @jwodder , I read the readme multiple times and I completely missed that.

Is there any way to specify these options in the pytest config file or in the pyprojext.toml?

**Comment by jwodder** [comment]
Yes, like all other pytest command-line options, you can specify them via pytest's [`addopts` config option](https://docs.pytest.org/en/stable/reference/reference.html#confval-addopts), e.g.:

```ini
[pytest]
addopts = --fail-slow-setup 5
```
