### ISSUE TITLE
consider supporting also setup time?

### ISSUE THREAD

**Issue by tapionx** [jwodder/pytest-fail-slow#4]
this plugin is not useful if you want to keep `setup` time under control.
I have fast tests, but with slow setup time.
Would you consider adding support for `setup` as well? maybe with a parameter to control the behavior

**Comment by jwodder** [comment]
@tapionx I've created a PR (#5) that adds a `@pytest.mark.fail_slow_setup(duration)` marker for failing a test if its setup takes too long.  Note the following:

* It checks the combined runtime of the setups of all fixtures, and only after they've all finished.  If each fixture takes less than the duration to run, but the sum of the runtimes is higher than the duration, the test will fail.  If one fixture takes more than the duration, fixtures after it will still be set up.
* If a test's setup takes too long, the test itself is not run.
* Fixture teardowns are still run.

Is this acceptable?

**Comment by jwodder** [comment]
This feature is now out in v0.4.0.
